name: CI

on: 
  push:
    branches: main
    
  workflow_dispatch:
  
jobs:
  build:
    run-on: ubuntu-latest
    
    steps: 
      - users: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello World!!!
      
    
